import { StyleSheet } from 'react-native';
import { appColors } from '../common';

export default StyleSheet.create({
    mainView:{
        backgroundColor:appColors.content,
    },
    bodyView:{
        width:'100%',
    },
    bodyContent:{
        paddingTop:50,
        marginHorizontal:'5%',
    },
    bodyHeading:{
        color:appColors.text,
        marginBottom:10,
    },
    bodyText:{
        color:appColors.text2,
        alignSelf:'center',
        textAlign:'center',
        marginVertical:10,
    },
    bodyCaption:{
        color:appColors.text3,
        alignSelf:'center',
        textAlign:'center',
        marginVertical:10,
    },
    textBox:{
        maxWidth:400,
        alignSelf:'center',
        width:'100%',
    },
    settingButtonText:{
        color:appColors.main,
    },
    settingButtonCaption:{
        color:appColors.main2,
    },
    settingButton:{
        alignSelf:'center',
        marginVertical:5,
        padding:10,
        borderRadius:5,
        maxWidth:400,
        width:'100%',
        flexDirection:'row',
        alignItems:'center',
    },
    settingButtonIcon:{
        marginRight:10,
    },
    creditsHeading:{
        color:appColors.text2,
        alignSelf:'center',
        textAlign:'center',
        marginTop:10,
    },
    creditsText:{
        color:appColors.text3,
        alignSelf:'center',
        textAlign:'center',
    },
});